name: amongi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: activate power ranger go
        run: source env/bin/activate
      - name: install
        run: ./env/bin/pip3.11 install -r requirements.txt
      - name: build it.
        uses: azure/appservice-build@v2
      - name: deeploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
